#!/usr/bin/env bash
# Assemble active incident rules into custom-rules.conf for the WAF container.
#
# Usage:
#   bash scripts/assemble_rules.sh                    # all incidents
#   bash scripts/assemble_rules.sh CVE-2025-55182     # specific incident(s)
#   bash scripts/assemble_rules.sh --list             # list available incidents
#   bash scripts/assemble_rules.sh --clear            # empty the active ruleset
#
# The assembled file is written to assets/docker/custom-rules.conf (or wherever
# the docker-compose mounts it from). After assembling, restart the active WAF.
# Uses docker compose if available, falls back to finch compose.

set -euo pipefail

# Auto-detect container runtime: docker compose → finch compose
if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v finch &>/dev/null; then
    COMPOSE="finch compose"
else
    COMPOSE="docker compose"  # default for display even if missing
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
INCIDENTS_DIR="${SKILL_DIR}/incidents"
OUTPUT="${SKILL_DIR}/assets/docker/custom-rules.conf"

# --- List mode ---
if [ "${1:-}" = "--list" ]; then
    echo "Available incidents:"
    if [ -d "$INCIDENTS_DIR" ]; then
        for d in "${INCIDENTS_DIR}"/*/; do
            [ -d "$d" ] || continue
            name=$(basename "$d")
            rules="$d/rules.conf"
            count=0
            if [ -f "$rules" ]; then
                count=$(grep -cE '^SecRule|^SecAction' "$rules" 2>/dev/null || true)
            fi
            echo "  ${name}  (${count} active rules)"
        done
    else
        echo "  (none — run scripts/new_incident.sh to create one)"
    fi
    exit 0
fi

# --- Clear mode ---
if [ "${1:-}" = "--clear" ]; then
    cat > "$OUTPUT" << 'EOF'
# Custom rules — currently empty.
# Use scripts/assemble_rules.sh to activate incident rules.
EOF
    echo "✓ Cleared: ${OUTPUT}"
    exit 0
fi

# --- Assemble ---
SELECTED=("$@")

{
    echo "# ============================================================"
    echo "# Assembled custom rules — generated by scripts/assemble_rules.sh"
    echo "# Date: $(date +%Y-%m-%dT%H:%M:%S)"
    echo "# Source incidents:"

    if [ ${#SELECTED[@]} -gt 0 ]; then
        for id in "${SELECTED[@]}"; do
            echo "#   - ${id}"
        done
    else
        echo "#   - (all)"
    fi
    echo "# ============================================================"
    echo ""

    RULE_COUNT=0
    INCIDENT_COUNT=0

    if [ -d "$INCIDENTS_DIR" ]; then
        for d in "${INCIDENTS_DIR}"/*/; do
            [ -d "$d" ] || continue
            name=$(basename "$d")
            rules="$d/rules.conf"

            # If specific incidents requested, skip non-matching
            if [ ${#SELECTED[@]} -gt 0 ]; then
                match=false
                for sel in "${SELECTED[@]}"; do
                    [ "$sel" = "$name" ] && match=true
                done
                $match || continue
            fi

            if [ -f "$rules" ] && grep -qE '^SecRule|^SecAction' "$rules" 2>/dev/null; then
                echo "# --- Incident: ${name} ---"
                cat "$rules"
                echo ""
                count=$(grep -cE '^SecRule|^SecAction' "$rules" 2>/dev/null || true)
                RULE_COUNT=$((RULE_COUNT + count))
                INCIDENT_COUNT=$((INCIDENT_COUNT + 1))
            fi
        done
    fi

    if [ "$RULE_COUNT" -eq 0 ]; then
        echo "# (no active rules)"
    fi
} > "$OUTPUT"

echo "✓ Assembled ${RULE_COUNT} rule(s) from ${INCIDENT_COUNT} incident(s) → ${OUTPUT}"
echo "  Restart WAF to apply (using ${COMPOSE}):"
echo "    ModSecurity: ${COMPOSE} -f assets/docker/docker-compose.yaml up -d"
echo "    Coraza:      ${COMPOSE} -f assets/docker/docker-compose.coraza.yaml up -d"
